SportsStore/Controllers/DynamicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.FileProviders;
using SportsStore.Data;
using SportsStore.Models;

namespace SportsStore.Controllers
{
    public class DynamicController : Controller
    {
        #region Constants

        private const string cshtml = ".cshtml";
        private const string editor = "Editor ";

        #endregion // Constants

        #region Fields

        private IViewRepository repository;
        private readonly IConfiguration _Config;
        private readonly ICMSService cmsService;

        #endregion // Fields

        #region Constructor

        public DynamicController(IViewRepository repo, IConfiguration config, ICMSService CMSService) {
            repository = repo;
            _Config = config;
            this.cmsService = CMSService;
        }

        #endregion // Constructor

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DisplayView(string view) {
            return View(view, new RazerView());
        }

        #region CRUD
        public async Task<IActionResult> Read()
        {
            
            //var result = await this.cmsService.ViewsGetAll();

            
            return View();
        }


        #endregion // CRUD

        public IActionResult Editor(string mode = "Editor", string location = "") {
            
            if (location == string.Empty && mode == string.Empty) { // We are creating a new model and we don't care about the view mode
                return View(new RazerView());
            } else {
                if (location == string.Empty) {   // We want a specific mode
                    return View(mode);
                } else {                          // Specific editor and existing model
                    try {
                        var provider = new ExampleDataProvider(_Config.GetConnectionString("CMSConnection"));
                        var view = provider.GetRazerView(location) ?? provider.GetRazerViewLikeLocation(location);
                        return View(mode, view ?? new RazerView());
                    } catch (Exception) {
                        return View(mode, new RazerView());
                    }
                }
            }
        }

        public IActionResult Search(string searchItems) {
            return View();
        }

        [HttpPost]
        public ViewResult SaveView(RazerView view) {
            if (ModelState.IsValid) {
                var provider = new ExampleDataProvider(_Config.GetConnectionString("CMSConnection"));
                var fromDb = provider.GetRazerView(view.RazerViewId) ?? provider.GetRazerView(view.Location) ?? provider.GetRazerViewLikeLocation(view.Location);
                if (fromDb != default(RazerView)) {
                    fromDb.HTMLContent  = view.HTMLContent;
                    fromDb.JSContent    = view.JSContent;
                    fromDb.CSSContent   = view.CSSContent;
                    fromDb.Model        = view.Model;
                    provider.UpdateRazerView(fromDb);
                } else {
                    provider.CreateRazerView(view);
                }
                return View("Thanks", view.Location);
            }
            return View();
        }
    }
}

SportsStore/Views/Shared/Headers/_Header.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<div class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a href="../" class="navbar-brand">CMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="../help/">Temp</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Dynamic")">Index</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Editors
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        @{
                            var value = HttpContextAccessor.HttpContext.Request.Cookies["Tab_Settings"];
                            if (value == null)
                            {
                                value = "Tabs (Columns)";
                            }
                        }

                        <a class="editor-style dropdown-item @(value == "Columns" ? "active" : "") " href="/Editor/Mode-Columns">Columns</a>
                        <a class="editor-style dropdown-item @(value == "Bottom Result" ? "active" : "") " href="/Editor/Mode-EditorBottomResult">Bottom Result</a>
                        <a class="editor-style dropdown-item @(value == "Right Result" ? "active" : "") " href="/Editor/Mode-RightResult">Right Result</a>
                        <a class="editor-style dropdown-item @(value == "Tabs (Columns)" ? "active" : "") " href="/Editor/Mode-TColumns">Tabs (Columns)</a>
                        <a class="editor-style dropdown-item @(value == "Tabs (Rows)" ? "active" : "") " href="/Editor/Mode-TRows">Tabs (Rows)</a>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav ms-md-auto">
                <li>
                    <div class="container-fluid">
                        <form class="d-flex" asp-action="Search" asp-controller="Dynamic">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </div>
                </li>
                <li class="nav-item">
                    <a target="_blank" rel="noopener" class="nav-link" href="#"><i class="fa fa-github"></i> GitHub</a>
                </li>
                <li class="nav-item">
                    <a target="_blank" rel="noopener" class="nav-link" href="#"><i class="fa fa-twitter"></i> Twitter</a>
                </li>
            </ul>
        </div>
    </div>
</div>